### ISSUE TITLE
Extra Data Packets

### ISSUE THREAD

**Issue by xloem** [kdewald/nativeble#10] opened 2021-01-28 23:14 UTC
I'm having an issue with the Muse where serial data is accumulating in the notifications multiple times.

I don't have this problem with other libraries.  I wonder if I am getting the data before the device receives the notification confirmation, in some way, so that it sends it again in the next update?  I noticed the backend is multithreaded.  Is this possible?

@kdewald 

Other backends I've tried include https://github.com/labapart/gattlib and https://github.com/hbldh/bleak .  Maybe the next step would be to try to copy bleak or gattlib's execution flow using simpledbus and try to narrow down what component the issue depends on or something =S  Maybe there's a way to take a dbus log and I could compare the dbus logs between two libraries.

note: `sudo dbus-monitor --system "sender=org.bluez"` may show the calls, from https://wiki.ubuntu.com/DebuggingDBus#Filtering_all_the_noise . I've found things can behave slightly differently depending on whether or not dbus-monitor is running, but it's still a very helpful tool.

**Comment by kdewald** [comment] 2021-01-28 23:22
I see this problem too, but haven't been able to pinpoint its origin. It
seems to be related with the speed at which events are being read from the
dbus message queue, but so far no luck.

**Comment by kdewald** [comment] 2021-01-29 07:26
I'm finally able to sit down and share everything I know about this bug:

I first noticed this issue when testing an application that streams large volumes of data that carry a sequence number at the front. What I saw were errors in which the sequence numbers were received twice, and the second time the payload would be larger than the first one, as if it were extended somehow. The issue was severe at first, but improved when I reduced the sleep time within `NativeBleInternal::async_thread_function()` to 50 microseconds. If you increase this delay, you'll definitely see the problem become worse.

I did some runs with `dbus-monitor` to track the issue, but without a fully reliable source of data it was too hard to reach any conclusions. I have yet to build a proper experimental setup where I can test this with a fully controlled data stream.

However, I did some tracking of the information flow within SimpleDBus and I'm 80% sure that these double calls don't originate internally, but come from some interaction happening either with the DBus socket or within `libdbus` (my money is on this last one). Regarding the multithreading question, it is possible that libdbus is spawning a thread internally, but I'm yet to confirm this.
One path forward would be to compile libdbus with debug flags and trace the events happening inside.

Regarding the other backends you mentioned:
- Gattlib uses GLib as its DBus backend, which handles all the message passing that goes back and forth. The reason I decided to go a different way was due to their structure not being friendly enough for the kind of usability I envisioned. They have plans to migrate towards a socket-based direct communication with DBus, which might cause the same types of issues we see right now.
- Bleak seems very interesting as well, but their underlying implementation is also using sockets to talk to DBus directly.

**Comment by xloem** [comment] 2021-01-29 07:35
> I first noticed this issue when testing an application that streams large volumes of data that carry a sequence number at the front. What I saw were errors in which the sequence numbers were received twice, and the second time the payload would be larger than the first one, as if it were extended somehow. The issue was severe at first, but improved when I reduced the sleep time within `NativeBleInternal::async_thread_function()` to 50 microseconds. If you increase this delay, you'll definitely see the problem become worse.

This is the exact same thing I experienced.  It happened quickly and reliably with the Muse.  The behavior as if new data is getting appended to a buffer of data that is not always getting emptied in time.

Does increasing the delay make the problem recur more reliably?

> However, I did some tracking of the information flow within SimpleDBus and I'm 80% sure that these double calls don't originate internally, but come from some interaction happening either with the DBus socket or within `libdbus` (my money is on this last one). Regarding the multithreading question, it is possible that libdbus is spawning a thread internally, but I'm yet to confirm this.
> One path forward would be to compile libdbus with debug flags and trace the events happening inside.

That sounds helpful.  A very simple testcase could be built with libdbus and whatever backend other systems use, to compare, too.

> * Gattlib uses GLib as its DBus backend, which handles all the message passing that goes back and forth. The reason I decided to go a different way was due to their structure not being friendly enough for the kind of usability I envisioned. They have plans to migrate towards a socket-based direct communication with DBus, which might cause the same types of issues we see right now.
> * Bleak seems very interesting as well, but their underlying implementation is also using sockets to talk to DBus directly.

Does libdbus not talk to DBus directly like these other systems do?

I have a medical obligation today but might be able to get to this.

**Comment by kdewald** [comment] 2021-01-29 07:45
> Does increasing the delay make the problem recur more reliably?

Yes, the original value of that delay was 1ms. If you change it to 500 microseconds it should happen quite often, especially if you're moving a large volume of data.

> Does libdbus not talk to DBus directly like these other systems do?

Yes, but libdbus handles the DBus socket and all the packing/unpacking logic, which is where this issue might arise.

> I have a medical obligation today but might be able to get to this.

Hope everything goes well! I'll plan to spend some time on this on the weekend for sure.

**Comment by xloem** [comment] 2021-01-29 08:24
Misbehavior does not occur in first commit.  Used `git bisect`.  Issue was introduced by commit c2eab5107f9b61e9f1053c48b8a706f1f1172396 .  I tried with different version of simpledbus and found the issue was introduced by either commit 87bec70475c54b12d9c84a3315d17ab43713d4b9 or c96b4d71b12588e891dec2e51759908a69a47bb1 (the checkout between the two had a different error for me).

Strangely, when I ran both original master branches together, the issue also occurred for me, could have been from stale build files.  EDIT: I recall I was running from OFF/ when master builds to bin/, so this was probably a state file situation.

**Comment by kdewald** [comment] 2021-01-30 06:04
The problem that got fixed in `87bec704` was a memory leak when passing Messages around that could corrupt the underlying DBus state. It also added caching of the message contents to avoid having to parse the dbus_message every time.

I did as much testing as I could back then to ensure that the reference counting and handling was correct, but I might have skipped something.

**Comment by xloem** [comment] 2021-01-30 11:33
the brainflow project wants to focus on using the bled112 dongle and its bglib library, so I might not be getting to this soon, unknown.  the world still definitely needs a cross-platform btle interface with a free license and an active maintainer.

My next step for debugging this would be to tease apart 87bec70475c54b12d9c84a3315d17ab43713d4b9 and test each of its conceptual changes, to see which one triggers the error.  I understand others could reproduce this error too by adjusting a timeout.

**Comment by kdewald** [comment] 2021-02-01 03:16
Ok, I've finally been able to set up an environment in which I can reproduce the issue consistently. I programmed an NRF52840 to push 4 payloads of 233 bytes at every connection interval into the transmission queue. The first two bytes correspond to a sequence number, the following byte to a subsequence number.

When calling `BlueZService.run_async()` every 10ms, the `ValueChanged` callback gets called with payload sizes of 233, 466 or 699 bytes long, which confirms that individual updates are somehow getting merged together. I'll start investigating deeper, but I'm optimistic that we'll sort this out pretty soon.

**Comment by kdewald** [comment] 2021-02-01 03:47
An example of what I just mentioned:
```
[VERBOSE] GattCharacteristic1.cpp (void GattCharacteristic1::add_option:23) /org/bluez/hci0/dev_CD_D8_2B_95_95_BF/service0016/char0019 -> ValueChanged
Array:
  ce ac 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 

Recv (233) Seq: 44238  Subseq: 0
[VERBOSE] GattCharacteristic1.cpp (void GattCharacteristic1::add_option:23) /org/bluez/hci0/dev_CD_D8_2B_95_95_BF/service0016/char0019 -> ValueChanged
Array:
  ce ac 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 cf ac 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 
  f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 

Recv (466) Seq: 44238  Subseq: 0
```
We first are getting one callback with the correct data, and with the next callback we're getting the new packet appended at the end of the previous one.

This is the incoming value to the `void GattCharacteristic1::add_option(std::string option_name, SimpleDBus::Holder value)` function, which means the underlying message or holder messed up or we are genuinely getting duplicated data from DBus.

**Comment by kdewald** [comment] 2021-02-03 07:37
So, I caught the event happening while using a compiled version of `libdbus` logging verbosely. I still need to go over it, but this way we have all the information we need.

[event.txt](https://github.com/kdewald/nativeble/files/5916827/event.txt)

**Comment by xloem** [comment] 2021-02-03 10:34
Do you know offhand how to enable that logging?
Comparing the output to a run that doesn't show the error might reveal whatever the differing property is.  I might try breaking into the commits that trigger the issue a little this morning.

**Comment by xloem** [comment] 2021-02-03 11:14
Reverting a small part of the commit in this way stops the issue in my test:

[tiny-partial-revert.patch.txt](https://github.com/kdewald/nativeble/files/5917980/tiny-partial-revert.patch.txt)

I'm noting that the call to pop_message within the loop is not calling read_write first, and wondering if this prevents the client's read of the data from being processed by dbus in time.

EDIT 2:
<i referenced some documentation here with concerns, but reading the documentation more i understand that simpledbus is not using message filters, but instead processing the incoming queue itself and not sharing its connection object.  still learning dbus.  it looks like the documentation would help a lot more if the approach were to use filters.>

**Comment by xloem** [comment] 2021-02-03 11:56
I'm still trying to understand this.  It looks like `dbus_connection_read_write_dispatch` performs important reply handling when it calls `dbus_connection_dispatch` (it passes replies to `dbus_connection_send_with_reply_and_block()`.  it also performs some valuable edge case handling, such as waiting when memory is exhausted).  It also processes one message from the queue when it does this.  Does this mean that `dbus_connection_pop_message` could miss some messages, or steal some from being dispatched and replied, since both are separately popping the queue?

**Comment by xloem** [comment] 2021-02-03 14:40
Here it is: in Holder.cpp, the assignment operator for arrays appends without clearing.  this makes data get concatenated when message objects are reused.  The loop form of run_async reuses the message object, if many messages have queued up.

@kdewald I'll probably make a PR for this <edit: removed expectation of it taking a while; this ended up finishing>

**Comment by kdewald** [comment] 2021-02-04 06:14
(Context: I went over your messages but I haven't seen your pull request as I'm writing this. I'll review that shortly.)

> Do you know offhand how to enable that logging?

- I cloned `libdbus-1` from here: https://gitlab.freedesktop.org/dbus/dbus
- `mkdir build && cd build`
- Compiled the library with the following options: 
  - `cmake -DDBUS_ENABLE_VERBOSE_MODE=ON -DCMAKE_BUILD_TYPE=Debug -DDBUS_SYSTEM_BUS_DEFAULT_ADDRESS=unix:path=/var/run/dbus/system_bus_socket  ..`
  - `make -j`
- I then copied `libdbus-1.so.3.29.0` and its symlinks to the same directory where `example_ble_nus` was created.
- I then ran the example with the following command:
  - ```LD_LIBRARY_PATH=`pwd` DBUS_VERBOSE=1 ./example_ble_nus $MAC_ADDRESS```
(I had modified the example a little bit to be more verbose in its output and I programmed my nRF52 dongle to start sending data the moment a BLE connection is established.)

Looking at the logs I was able to find the event I shared with you. In there we can confirm that from the perspective of `libdbus`:
- Message `0x5562a34ef4f0` arrives. Queue size is 1.
- Message `0x5562a35640d0` arrives. Queue size is 2.
- Message `0x5562a34ef4f0` is popped. Queue size is 1.
- Contents of message `0x5562a34ef4f0` are printed out by `example_ble_nus`.
- Message `0x5562a35640d0` is popped. Queue size is 0.
- `example_ble_nus` now prints the contents of `0x5562a34ef4f0` and `0x5562a35640d0` together.

Without any additional information, this at least confirms that the root cause of the problem has to be internal to SimpleDBus, as messages are being popped and processed individually. I'm sure your fix is directly addressing this issue, that some internal state/variable is not getting cleared and is then reused.

**Comment by kdewald** [comment] 2021-02-04 06:35
> I'm noting that the call to pop_message within the loop is not calling read_write first, and wondering if this prevents the client's read of the data from being processed by dbus in time.

From my understanding of the documentation, the pop_message and read_write processes are distinct.
- The read_write functionality sends any queued outgoing messages and then reads the socket to see if there are any incoming ones. Any new incoming message will be added to the incoming queue.
- The pop_message attempts to pop a message from the incoming queue or returns a null pointer (which the `Message` class will interpret as an invalid one).
As far as I understand this, there shouldn't be any issues with this scheme. Basically every time after running read_write we pop all messages from the queue and process them asap.

> EDIT 2:
> <i referenced some documentation here with concerns, but reading the documentation more i understand that simpledbus is not using message filters, but instead processing the incoming queue itself and not sharing its connection object. still learning dbus. it looks like the documentation would help a lot more if the approach were to use filters.>

SimpleDBus uses only one filter so far:
```
void BluezService::init() {
    conn.init();
    object_manager.GetManagedObjects(true);  // Feed the objects via callback.

    conn.add_match("type='signal',sender='org.bluez'");
}
```
This filter means that we're only listening to updates coming from `org.bluez`, the Linux BLE controller. The only thing I'm not sure of is how this might affect if multiple processes are running and for some reason they need to keep track of each other.

**Comment by xloem** [comment] 2021-02-04 13:35
Well, I still don't understand dbus well.

> > I'm noting that the call to pop_message within the loop is not calling read_write first, and wondering if this prevents the client's read of the data from being processed by dbus in time.
> 
> From my understanding of the documentation, the pop_message and read_write processes are distinct.
> 
> * The read_write functionality sends any queued outgoing messages and then reads the socket to see if there are any incoming ones. Any new incoming message will be added to the incoming queue.
> * The pop_message attempts to pop a message from the incoming queue or returns a null pointer (which the `Message` class will interpret as an invalid one).
>   As far as I understand this, there shouldn't be any issues with this scheme. Basically every time after running read_write we pop all messages from the queue and process them asap.

SimpleDBus is presently using [`dbus_connection_read_write_dispatch`](https://github.com/kdewald/SimpleDBus/blame/fe8cfb61dbbc454c6db28791a29976cbfbc90a0a/src/simpledbus/base/Connection.cpp#L57) which [tests when dispatching is needed and calls `dbus_connection_dispatch`](https://gitlab.freedesktop.org/dbus/dbus/-/blob/master/dbus/dbus-connection.c#L3690), skipping processing the queue when that happens.  I don't understand under what conditions that `DBUS_DISPATCH_DATA_REMAINS` flag is true.  It is likely when the queue is not empty as you describe -- but if that's true then it would be more clear to simply call `dbus_connection_read_write` as the dispatch would never happen.   `dbus_connection_dispatch` [performs its own `pop_message` once](https://gitlab.freedesktop.org/dbus/dbus/-/blob/master/dbus/dbus-connection.c#L4605) which is [documented](https://dbus.freedesktop.org/doc/api/html/group__DBusConnection.html#ga66ba7df50d75f4bda6b6e942430b81c7), which if allowed to happen looks like it could steal a message from simpledbus under the current scheme.

This is why while debugging I implemented `borrow_message` to see if letting all the messages be dispatched helped in any way.  The functionality of what I tested seemed roughly the same to me between `borrow_message` and `pop_message`.

> > EDIT 2:
> > <i referenced some documentation here with concerns, but reading the documentation more i understand that simpledbus is not using message filters, but instead processing the incoming queue itself and not sharing its connection object. still learning dbus. it looks like the documentation would help a lot more if the approach were to use filters.>
> 
> SimpleDBus uses only one filter so far:
> 
> ```
> void BluezService::init() {
>     conn.init();
>     object_manager.GetManagedObjects(true);  // Feed the objects via callback.
> 
>     conn.add_match("type='signal',sender='org.bluez'");
> }
> ```
> 
> This filter means that we're only listening to updates coming from `org.bluez`, the Linux BLE controller. The only thing I'm not sure of is how this might affect if multiple processes are running and for some reason they need to keep track of each other.

At a glance it looks like using [`dbus_connection_add_filter`](https://dbus.freedesktop.org/doc/api/html/group__DBusConnection.html#gae00f581e5487408cb294bf71826aff86) to process those messages would let dbus keep track of things better.  I think for that function to work the call to `pop_message` would have to be removed, as `add_filter` would replace it.  I think this approach doesn't matter here because the connection object is never shared; the only improvement might be code clarity and consistency with docs.

**Closed as completed** 2021-02-04 13:41 UTC
Labels: bug
